global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'micronaut-app'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'micronaut-micro-service'
