database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:micro_notes}
  user: ${DATABASE_USER}
  pass: ${DATABASE_PASS}

jaeger:
  host: ${JAEGER_HOST:localhost}
  port: ${JAEGER_OTLP_PORT:4317}

micronaut:
  application:
    name: micronautMicroService
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
      swagger:
        enabled: true
        mapping: /swagger/**
        paths: classpath:META-INF/swagger
      swagger-ui:
        enabled: true
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
  openapi:
    views:
      spec: "swagger-ui.enabled=true"
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

otel:
  traces:
    exporter: otlp
    sampler: always_on
  exporter:
    otlp:
      endpoint: http://${jaeger.host}:${jaeger.port}

endpoints:
  prometheus:
    sensitive: false

datasources:
  default:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    schema: ${database.name}
    username: ${database.user}
    password: ${database.pass}
    driverClassName: org.postgresql.Driver

flyway:
  datasources:
    default:
      enabled: true
      default-schema: ${database.name}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

netty:
  default:
    allocator:
      max-order: 10

logger:
  levels:
    io.micronaut.http: TRACE
    io.micronaut.http.body.ByteBody: WARN
