database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  schema: ${DATABASE_SCHEMA:micro_notes}
  user: ${DATABASE_USER}
  pass: ${DATABASE_PASS}

micronaut:
  application:
    name: micronautMicroService

datasources:
  default:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.schema}
    username: ${database.user}
    password: ${database.pass}
    driverClassName: org.postgresql.Driver

flyway:
  datasources:
    default:
      enabled: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

netty:
  default:
    allocator:
      max-order: 3

logger:
  levels:
    io.micronaut.http: TRACE
