database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:micro_notes}
  user: ${DATABASE_USER}
  pass: ${DATABASE_PASS}

micronaut:
  application:
    name: micronautMicroService
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
  caches:
    notes:
      redis:
        charset: UTF-8
        expire-after-write: 60m
    tags:
      redis:
        charset: UTF-8
        expire-after-write: 60m

datasources:
  default:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.user}
    password: ${database.pass}
    driverClassName: org.postgresql.Driver

flyway:
  datasources:
    default:
      enabled: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

netty:
  default:
    allocator:
      max-order: 10

logger:
  levels:
    io.micronaut.http: TRACE
    io.micronaut.http.body.ByteBody: WARN
    io.micronaut.cache: DEBUG
    io.micronaut.redis: DEBUG

redis:
  uri: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
  caches:
    notes:
      charset: UTF-8
      expire-after-write: 60m
    tags:
      charset: UTF-8
      expire-after-write: 60m
