GET http://localhost:8080/customers/1

###

POST http://localhost:8080/customers
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@domain.com"
}

###

PATCH http://localhost:8080/customers/1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Deere",
  "email": "john.deere@deere.com"
}

###

DELETE http://localhost:8080/customers/1