GET http://localhost:8080/products/1

###

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "piece of junk",
  "price": 999.66
}

###

PATCH http://localhost:8080/products/1
Content-Type: application/json

{
  "name": "shiny piece of junk",
  "description": "Real nice piece of junk!",
  "price": 100500.66
}

###

DELETE http://localhost:8080/products/1